[server]
port = $PORT
headless = true
enableCORS = false
enableXsrfProtection = false
allowEmbedding = true

[theme]
base = "light"
primaryColor = "#000000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f7"
textColor = "#000000"
font = "sans serif"
