[server]
headless = true
enableCORS = false
enableXsrfProtection = false
allowEmbedding = true

[theme]
base = "light"
primaryColor = "#000000"                     # Pure black for buttons and highlights
backgroundColor = "#ffffff"                  # True white background
secondaryBackgroundColor = "#f7f7f7"         # Very light gray for cards and sidebars
textColor = "#000000"                        # Solid black text
font = "sans serif"                          # Use "sans serif", "monospace", or "serif"
